### ISSUE TITLE
Need to change the dynamic configuration implementation.

### ISSUE THREAD

**Issue by HanumantappaBudihal** [HugoByte/aurras-event-feed-substrate-js#4]
Logger configurations should be loaded as array of logger configuration objects.

Please Include the below implementation 

1. Add the module to validated the array of list in json file.( list of logger configurations). Make it very generic module , so we can use the same json validator in other part also.
2. Parse the single line logger configuration values into proper json structure.
    something like  Type : console ,
                              Level : Info
                              Location : Console output
3. System should assign the proper values each properties regardless the order in the configuration file.  
4. Logger Configuration passed through environment variable should have type, level, and location

Link to PR with this issue #2

**Comment by MuhammedIrfan** [comment]
Closing as not needed in current implementation. Might open in future
