### ISSUE TITLE
Fix the naming convention for unit test method and format.

### ISSUE THREAD

**Issue by HanumantappaBudihal** [HugoByte/aurras-event-feed-substrate-js#7]
Decide the naming convention for unit test methods.

Unit test method should explain the what part the code is tested by the unit test method.

**Comment by MuhammedIrfan** [comment]
**Suite Description:** Should be a single line information.

**Test Name:** Should explain the unit test case (for eg: Can throw error if logger transport provided is invalid)
```
describe("Logger Helper Unit Tests", () => {
    test("Can throw error if logger transport provided is invalid", () => {
        # Test Implementation
    });

    test("Can return console transport", () => {
        # Test Implementation
    });
});
```
